### ISSUE TITLE
`::selection`  style conflicts the app's selection default style

### ISSUE THREAD

**Issue by softmarshmallow** [Aslam97/shadcn-minimal-tiptap#101]
<img width="363" alt="Image" src="https://github.com/user-attachments/assets/013080f6-316e-4127-90d6-cc4c9fff8fd8" />

This part of the `styles/index.css` makes the default selection color affects the app's default style.

```css
.minimal-tiptap-editor .ProseMirror .selection,
.minimal-tiptap-editor .ProseMirror *::selection,
::selection {
  @apply bg-primary/25;
}

/* Override native selection when custom selection is present */
.minimal-tiptap-editor .ProseMirror .selection::selection {
  background: transparent;
}
```

Also, what is the purpose of this? - I think this part does not contribute to the styles meaningfully?
